---
driver:
  name: vagrant
  product_version: 14.1.1

provisioner:
  name: chef_zero
  nodes_path: 'test/fixtures/nodes'
  environments_path: 'test/fixtures/environments'
  data_bags_path: 'test/fixtures/data_bags'
  client_rb:
    environment: _default

verifier:
  name: inspec

platforms:
  - name: opscode-ubuntu-18.04-chef-14
    driver:
      box: bento/ubuntu-18.04
    provisioner:
      product_name: chef
      product_version: latest

suites:
  - name: app
    run_list:
      - recipe[barito_market::db]
      - recipe[barito_market::app]
    verifier:
      inspec_tests:
        - test/integration/app
        - test/unit/spec
    attributes:
      app_name: "baritoMarket"