---
driver:
  name: vagrant
  product_version: 14.1.1
  network:
  - ["forwarded_port", {guest: 8080, host: 8080}]

provisioner:
  name: chef_zero
  nodes_path: 'test/fixtures/nodes'
  environments_path: 'test/fixtures/environments'
  data_bags_path: 'test/fixtures/data_bags'
  client_rb:
    environment: _default

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[barito_market::default]
    verifier:
      inspec_tests:
        - test/unit/spec
    attributes:
      app_name: "baritoMarket"
      market_script_location: "/opt/baritoMarket/baritoMarket/run.sh"
      command_name: "rails server -p 8080"
