---
driver:
  name: vagrant
  product_version: 14.1.1

provisioner:
  name: chef_zero
  nodes_path: 'test/fixtures/nodes'
  environments_path: 'test/fixtures/environments'
  data_bags_path: 'test/fixtures/data_bags'
  client_rb:
    environment: _default

verifier:
  name: inspec

platforms:
  - name: opscode-ubuntu-18.04-chef-14
    driver:
      box: bento/ubuntu-18.04
    provisioner:
      product_name: chef
      product_version: latest

suites:
  - name: master
    run_list:
      - recipe[barito_market::db]
      - recipe[barito_market::app]
    driver_config:
      customize:
        memory: 1024
      network:
        - ['private_network', {ip: '192.168.33.10'}]
    verifier:
      inspec_tests:
        - test/integration/app
        - test/unit/spec
    attributes:
      app_name: "baritoMarket"
      postgresql:
        replication: true
        db_replication_addr: '192.168.33.11'
        db_replication_username: 'repluser'
        db_replication_password: 'password1234'
  - name: slave
    run_list:
      - recipe[barito_market::db_slave]
    driver_config:
      customize:
        memory: 1024
      network:
        - ['private_network', {ip: '192.168.33.11'}]
    verifier:
      inspec_tests:
        - test/integration/app
        - test/unit/spec
    attributes:
      app_name: "baritoMarket"
      postgresql:
        db_master_address: '192.168.33.10'
        db_replication_username: 'repluser'
        db_replication_password: 'password1234'
